import type { Metadata } from "next";
import "./globals.css";
import ProgressBar from "@/components/common/ProgressBar";
import { Roboto } from "next/font/google";
import { cn } from "@/utils/utils";
import Sidebar from "@/components/ui/Sidebar";
import ClientContext from "@/context/ClientContext";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hệ thống quản lý trực tuyến - [CLOSEAI]",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/ictu.png" />
        <link rel="shortcut icon" href="/ictu.png" type="image/x-icon" />
      </head>
      <body className={cn("antialiased bg-white", roboto.variable)}>
        <ClientContext>
          <ProgressBar />
          <Toaster
            position="bottom-left"
            gutter={16}
            toastOptions={{ duration: 6000 }}
          />
          <main className="flex w-screen h-svh">{children}</main>
        </ClientContext>
      </body>
    </html>
  );
}
